### ISSUE TITLE
No module found Pythoncom

### ISSUE THREAD

**Issue by jamesxwang** [denisenkom/django-sqlserver#17]
I use Python 3.4, Django1.8.18, django-mssql 1.8 and django-sqlserver 1.11. But when I run server, an error message comes up 'No module found Pythoncom'. Could you please help?

**Comment by denisenkom** [comment]
can you provide a stack trace?

**Comment by jamesxwang** [comment]
many thanks for the prompt response.

what I want to achieve is to use django-mssql but without pywin32 as I will need to use it in a Linux environment.

I am new to django so I am not sure what you mean by stack trace.

but please see attached a screen shot of my Command Prompt:
- at the top, you could see the structure of my project folder (for the testing purpose, I have just created a new django project without any app)
- then you could see all the packages I have install with their version
- lastly you could see the error message

I did try django-sqlserver with python 3.4, django 1.6 and django-mssql 1.6 and I did not received the error message. however, django 1.6 is no longer supported so I will need django 1.8.18 at least.

it will be great if you could have a look! Thanks again!
[Doc1.docx](https://github.com/denisenkom/django-sqlserver/files/1230767/Doc1.docx)

**Comment by denisenkom** [comment]
I think you are using django-mssql database driver in your Django configuration file.  If this is so you should switch to django-sqlserver driver.  If this is not the case please upload your Django configuration file.
