### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by kottenator** [denisenkom/django-sqlserver#7]
Hi!

I'm using django-sqlserver in my project (Django 1.7.7, Python 3.4).

I tried to switch to Django 1.8c1 and it seems that they've made a lot of changes in django.db so django-sqlserver doesn't work anymore.

Are you going to implement Django 1.8 support soon? 

Your project is pretty unique, I can't find any alternatives so far, so I count on you

**Comment by denisenkom** [comment]
django-sqlserver is basically an add-on to django-mssql which adds support for pytds.  Ideally it will contain only minimum amount of code to make django-mssql to work with pytds.
Therefore the support for Django 1.8 should first be added to django-mssql, then it will probably "just work" with django-sqlserver.

**Comment by kottenator** [comment]
Thanks for the explanation. I tried to use the latest commit from django-mssql with your lib and it doesn't work with Django 1.8. Probably they have not implemented is support yet. I've created [a ticket](https://bitbucket.org/Manfre/django-mssql/issue/71/django-18-support) for them

**Comment by adriaant** [comment]
Unfortunately it doesn't "just work" in Django 1.8. The code uses methods that do not exist in the new DB API. I've forked the repo and am trying to make compatibility fixes.

**Comment by yousseb** [comment]
Put this in your requirements.txt
-e git+https://bitbucket.org/Manfre/django-mssql.git@bf1a60b#egg=django-mssql-1.71

**Comment by denisenkom** [comment]
I created branch django1.8-support, take a look.
It requires latest version of django-mssql from git (version from pypi wouldn't work).

**Comment by chetmancini** [comment]
I'm using Django 1.8.7 and I've copied the code directly down from `master` as of `d326ef77da62991f2ecdb289fe00c9a021eda1cc` and it's working great. Are there further issues to resolve before cutting a new version on PyPi?

**Comment by denisenkom** [comment]
Uploaded version 1.9: https://pypi.python.org/pypi/django-sqlserver/1.9

**Comment by chetmancini** [comment]
@denisenkom amazing--working great. thank you!
